// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	"avito/internal/oapi"
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPvzService creates a new instance of MockPvzService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPvzService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPvzService {
	mock := &MockPvzService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPvzService is an autogenerated mock type for the PvzService type
type MockPvzService struct {
	mock.Mock
}

type MockPvzService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPvzService) EXPECT() *MockPvzService_Expecter {
	return &MockPvzService_Expecter{mock: &_m.Mock}
}

// AddProduct provides a mock function for the type MockPvzService
func (_mock *MockPvzService) AddProduct(ctx context.Context, pvzID uuid.UUID, productType oapi.ProductType) (oapi.Product, error) {
	ret := _mock.Called(ctx, pvzID, productType)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 oapi.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, oapi.ProductType) (oapi.Product, error)); ok {
		return returnFunc(ctx, pvzID, productType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, oapi.ProductType) oapi.Product); ok {
		r0 = returnFunc(ctx, pvzID, productType)
	} else {
		r0 = ret.Get(0).(oapi.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, oapi.ProductType) error); ok {
		r1 = returnFunc(ctx, pvzID, productType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPvzService_AddProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduct'
type MockPvzService_AddProduct_Call struct {
	*mock.Call
}

// AddProduct is a helper method to define mock.On call
//   - ctx
//   - pvzID
//   - productType
func (_e *MockPvzService_Expecter) AddProduct(ctx interface{}, pvzID interface{}, productType interface{}) *MockPvzService_AddProduct_Call {
	return &MockPvzService_AddProduct_Call{Call: _e.mock.On("AddProduct", ctx, pvzID, productType)}
}

func (_c *MockPvzService_AddProduct_Call) Run(run func(ctx context.Context, pvzID uuid.UUID, productType oapi.ProductType)) *MockPvzService_AddProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(oapi.ProductType))
	})
	return _c
}

func (_c *MockPvzService_AddProduct_Call) Return(product oapi.Product, err error) *MockPvzService_AddProduct_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockPvzService_AddProduct_Call) RunAndReturn(run func(ctx context.Context, pvzID uuid.UUID, productType oapi.ProductType) (oapi.Product, error)) *MockPvzService_AddProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePvz provides a mock function for the type MockPvzService
func (_mock *MockPvzService) CreatePvz(ctx context.Context, city oapi.PVZCity) (oapi.PVZ, error) {
	ret := _mock.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for CreatePvz")
	}

	var r0 oapi.PVZ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.PVZCity) (oapi.PVZ, error)); ok {
		return returnFunc(ctx, city)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.PVZCity) oapi.PVZ); ok {
		r0 = returnFunc(ctx, city)
	} else {
		r0 = ret.Get(0).(oapi.PVZ)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oapi.PVZCity) error); ok {
		r1 = returnFunc(ctx, city)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPvzService_CreatePvz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePvz'
type MockPvzService_CreatePvz_Call struct {
	*mock.Call
}

// CreatePvz is a helper method to define mock.On call
//   - ctx
//   - city
func (_e *MockPvzService_Expecter) CreatePvz(ctx interface{}, city interface{}) *MockPvzService_CreatePvz_Call {
	return &MockPvzService_CreatePvz_Call{Call: _e.mock.On("CreatePvz", ctx, city)}
}

func (_c *MockPvzService_CreatePvz_Call) Run(run func(ctx context.Context, city oapi.PVZCity)) *MockPvzService_CreatePvz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oapi.PVZCity))
	})
	return _c
}

func (_c *MockPvzService_CreatePvz_Call) Return(pVZ oapi.PVZ, err error) *MockPvzService_CreatePvz_Call {
	_c.Call.Return(pVZ, err)
	return _c
}

func (_c *MockPvzService_CreatePvz_Call) RunAndReturn(run func(ctx context.Context, city oapi.PVZCity) (oapi.PVZ, error)) *MockPvzService_CreatePvz_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLastProduct provides a mock function for the type MockPvzService
func (_mock *MockPvzService) DeleteLastProduct(ctx context.Context, pvzID uuid.UUID) error {
	ret := _mock.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLastProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, pvzID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPvzService_DeleteLastProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLastProduct'
type MockPvzService_DeleteLastProduct_Call struct {
	*mock.Call
}

// DeleteLastProduct is a helper method to define mock.On call
//   - ctx
//   - pvzID
func (_e *MockPvzService_Expecter) DeleteLastProduct(ctx interface{}, pvzID interface{}) *MockPvzService_DeleteLastProduct_Call {
	return &MockPvzService_DeleteLastProduct_Call{Call: _e.mock.On("DeleteLastProduct", ctx, pvzID)}
}

func (_c *MockPvzService_DeleteLastProduct_Call) Run(run func(ctx context.Context, pvzID uuid.UUID)) *MockPvzService_DeleteLastProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPvzService_DeleteLastProduct_Call) Return(err error) *MockPvzService_DeleteLastProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPvzService_DeleteLastProduct_Call) RunAndReturn(run func(ctx context.Context, pvzID uuid.UUID) error) *MockPvzService_DeleteLastProduct_Call {
	_c.Call.Return(run)
	return _c
}

// FinishReception provides a mock function for the type MockPvzService
func (_mock *MockPvzService) FinishReception(ctx context.Context, pvzID uuid.UUID) (oapi.Reception, error) {
	ret := _mock.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for FinishReception")
	}

	var r0 oapi.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (oapi.Reception, error)); ok {
		return returnFunc(ctx, pvzID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) oapi.Reception); ok {
		r0 = returnFunc(ctx, pvzID)
	} else {
		r0 = ret.Get(0).(oapi.Reception)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPvzService_FinishReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishReception'
type MockPvzService_FinishReception_Call struct {
	*mock.Call
}

// FinishReception is a helper method to define mock.On call
//   - ctx
//   - pvzID
func (_e *MockPvzService_Expecter) FinishReception(ctx interface{}, pvzID interface{}) *MockPvzService_FinishReception_Call {
	return &MockPvzService_FinishReception_Call{Call: _e.mock.On("FinishReception", ctx, pvzID)}
}

func (_c *MockPvzService_FinishReception_Call) Run(run func(ctx context.Context, pvzID uuid.UUID)) *MockPvzService_FinishReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPvzService_FinishReception_Call) Return(reception oapi.Reception, err error) *MockPvzService_FinishReception_Call {
	_c.Call.Return(reception, err)
	return _c
}

func (_c *MockPvzService_FinishReception_Call) RunAndReturn(run func(ctx context.Context, pvzID uuid.UUID) (oapi.Reception, error)) *MockPvzService_FinishReception_Call {
	_c.Call.Return(run)
	return _c
}

// ListPVZInfo provides a mock function for the type MockPvzService
func (_mock *MockPvzService) ListPVZInfo(ctx context.Context, params oapi.GetPvzParams) ([]oapi.GetPvzResponseItem, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListPVZInfo")
	}

	var r0 []oapi.GetPvzResponseItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.GetPvzParams) ([]oapi.GetPvzResponseItem, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.GetPvzParams) []oapi.GetPvzResponseItem); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]oapi.GetPvzResponseItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oapi.GetPvzParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPvzService_ListPVZInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPVZInfo'
type MockPvzService_ListPVZInfo_Call struct {
	*mock.Call
}

// ListPVZInfo is a helper method to define mock.On call
//   - ctx
//   - params
func (_e *MockPvzService_Expecter) ListPVZInfo(ctx interface{}, params interface{}) *MockPvzService_ListPVZInfo_Call {
	return &MockPvzService_ListPVZInfo_Call{Call: _e.mock.On("ListPVZInfo", ctx, params)}
}

func (_c *MockPvzService_ListPVZInfo_Call) Run(run func(ctx context.Context, params oapi.GetPvzParams)) *MockPvzService_ListPVZInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oapi.GetPvzParams))
	})
	return _c
}

func (_c *MockPvzService_ListPVZInfo_Call) Return(getPvzResponseItems []oapi.GetPvzResponseItem, err error) *MockPvzService_ListPVZInfo_Call {
	_c.Call.Return(getPvzResponseItems, err)
	return _c
}

func (_c *MockPvzService_ListPVZInfo_Call) RunAndReturn(run func(ctx context.Context, params oapi.GetPvzParams) ([]oapi.GetPvzResponseItem, error)) *MockPvzService_ListPVZInfo_Call {
	_c.Call.Return(run)
	return _c
}

// StartReception provides a mock function for the type MockPvzService
func (_mock *MockPvzService) StartReception(ctx context.Context, pvzID uuid.UUID) (oapi.Reception, error) {
	ret := _mock.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for StartReception")
	}

	var r0 oapi.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (oapi.Reception, error)); ok {
		return returnFunc(ctx, pvzID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) oapi.Reception); ok {
		r0 = returnFunc(ctx, pvzID)
	} else {
		r0 = ret.Get(0).(oapi.Reception)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPvzService_StartReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartReception'
type MockPvzService_StartReception_Call struct {
	*mock.Call
}

// StartReception is a helper method to define mock.On call
//   - ctx
//   - pvzID
func (_e *MockPvzService_Expecter) StartReception(ctx interface{}, pvzID interface{}) *MockPvzService_StartReception_Call {
	return &MockPvzService_StartReception_Call{Call: _e.mock.On("StartReception", ctx, pvzID)}
}

func (_c *MockPvzService_StartReception_Call) Run(run func(ctx context.Context, pvzID uuid.UUID)) *MockPvzService_StartReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockPvzService_StartReception_Call) Return(reception oapi.Reception, err error) *MockPvzService_StartReception_Call {
	_c.Call.Return(reception, err)
	return _c
}

func (_c *MockPvzService_StartReception_Call) RunAndReturn(run func(ctx context.Context, pvzID uuid.UUID) (oapi.Reception, error)) *MockPvzService_StartReception_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// GetRoleFromReq provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetRoleFromReq(bearerToken string) (oapi.UserRole, error) {
	ret := _mock.Called(bearerToken)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleFromReq")
	}

	var r0 oapi.UserRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (oapi.UserRole, error)); ok {
		return returnFunc(bearerToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) oapi.UserRole); ok {
		r0 = returnFunc(bearerToken)
	} else {
		r0 = ret.Get(0).(oapi.UserRole)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bearerToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetRoleFromReq_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleFromReq'
type MockAuthService_GetRoleFromReq_Call struct {
	*mock.Call
}

// GetRoleFromReq is a helper method to define mock.On call
//   - bearerToken
func (_e *MockAuthService_Expecter) GetRoleFromReq(bearerToken interface{}) *MockAuthService_GetRoleFromReq_Call {
	return &MockAuthService_GetRoleFromReq_Call{Call: _e.mock.On("GetRoleFromReq", bearerToken)}
}

func (_c *MockAuthService_GetRoleFromReq_Call) Run(run func(bearerToken string)) *MockAuthService_GetRoleFromReq_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthService_GetRoleFromReq_Call) Return(userRole oapi.UserRole, err error) *MockAuthService_GetRoleFromReq_Call {
	_c.Call.Return(userRole, err)
	return _c
}

func (_c *MockAuthService_GetRoleFromReq_Call) RunAndReturn(run func(bearerToken string) (oapi.UserRole, error)) *MockAuthService_GetRoleFromReq_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenForRole provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetTokenForRole(ctx context.Context, role oapi.UserRole) (string, error) {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenForRole")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.UserRole) (string, error)); ok {
		return returnFunc(ctx, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.UserRole) string); ok {
		r0 = returnFunc(ctx, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oapi.UserRole) error); ok {
		r1 = returnFunc(ctx, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetTokenForRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenForRole'
type MockAuthService_GetTokenForRole_Call struct {
	*mock.Call
}

// GetTokenForRole is a helper method to define mock.On call
//   - ctx
//   - role
func (_e *MockAuthService_Expecter) GetTokenForRole(ctx interface{}, role interface{}) *MockAuthService_GetTokenForRole_Call {
	return &MockAuthService_GetTokenForRole_Call{Call: _e.mock.On("GetTokenForRole", ctx, role)}
}

func (_c *MockAuthService_GetTokenForRole_Call) Run(run func(ctx context.Context, role oapi.UserRole)) *MockAuthService_GetTokenForRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oapi.UserRole))
	})
	return _c
}

func (_c *MockAuthService_GetTokenForRole_Call) Return(s string, err error) *MockAuthService_GetTokenForRole_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthService_GetTokenForRole_Call) RunAndReturn(run func(ctx context.Context, role oapi.UserRole) (string, error)) *MockAuthService_GetTokenForRole_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, email string, password string) (string, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx
//   - email
//   - password
func (_e *MockAuthService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(s string, err error) *MockAuthService_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (string, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, role oapi.UserRole, email string, password string) (oapi.User, error) {
	ret := _mock.Called(ctx, role, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 oapi.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.UserRole, string, string) (oapi.User, error)); ok {
		return returnFunc(ctx, role, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.UserRole, string, string) oapi.User); ok {
		r0 = returnFunc(ctx, role, email, password)
	} else {
		r0 = ret.Get(0).(oapi.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oapi.UserRole, string, string) error); ok {
		r1 = returnFunc(ctx, role, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx
//   - role
//   - email
//   - password
func (_e *MockAuthService_Expecter) Register(ctx interface{}, role interface{}, email interface{}, password interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, role, email, password)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, role oapi.UserRole, email string, password string)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oapi.UserRole), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(user oapi.User, err error) *MockAuthService_Register_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, role oapi.UserRole, email string, password string) (oapi.User, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}
