// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_service

import (
	"avito/internal/oapi"
	"context"

	"github.com/oapi-codegen/runtime/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateUser(ctx context.Context, role oapi.UserRole, email string, password string) (types.UUID, error) {
	ret := _mock.Called(ctx, role, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 types.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.UserRole, string, string) (types.UUID, error)); ok {
		return returnFunc(ctx, role, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.UserRole, string, string) types.UUID); ok {
		r0 = returnFunc(ctx, role, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oapi.UserRole, string, string) error); ok {
		r1 = returnFunc(ctx, role, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx
//   - role
//   - email
//   - password
func (_e *MockRepository_Expecter) CreateUser(ctx interface{}, role interface{}, email interface{}, password interface{}) *MockRepository_CreateUser_Call {
	return &MockRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, role, email, password)}
}

func (_c *MockRepository_CreateUser_Call) Run(run func(ctx context.Context, role oapi.UserRole, email string, password string)) *MockRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oapi.UserRole), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_CreateUser_Call) Return(v types.UUID, err error) *MockRepository_CreateUser_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, role oapi.UserRole, email string, password string) (types.UUID, error)) *MockRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRole provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserRole(ctx context.Context, email string, password string) (oapi.UserRole, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRole")
	}

	var r0 oapi.UserRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (oapi.UserRole, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) oapi.UserRole); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		r0 = ret.Get(0).(oapi.UserRole)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRole'
type MockRepository_GetUserRole_Call struct {
	*mock.Call
}

// GetUserRole is a helper method to define mock.On call
//   - ctx
//   - email
//   - password
func (_e *MockRepository_Expecter) GetUserRole(ctx interface{}, email interface{}, password interface{}) *MockRepository_GetUserRole_Call {
	return &MockRepository_GetUserRole_Call{Call: _e.mock.On("GetUserRole", ctx, email, password)}
}

func (_c *MockRepository_GetUserRole_Call) Run(run func(ctx context.Context, email string, password string)) *MockRepository_GetUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetUserRole_Call) Return(userRole oapi.UserRole, err error) *MockRepository_GetUserRole_Call {
	_c.Call.Return(userRole, err)
	return _c
}

func (_c *MockRepository_GetUserRole_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (oapi.UserRole, error)) *MockRepository_GetUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTHelper creates a new instance of MockJWTHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTHelper {
	mock := &MockJWTHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTHelper is an autogenerated mock type for the JWTHelper type
type MockJWTHelper struct {
	mock.Mock
}

type MockJWTHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTHelper) EXPECT() *MockJWTHelper_Expecter {
	return &MockJWTHelper_Expecter{mock: &_m.Mock}
}

// GetRoleClaim provides a mock function for the type MockJWTHelper
func (_mock *MockJWTHelper) GetRoleClaim(tokenString string) (oapi.UserRole, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleClaim")
	}

	var r0 oapi.UserRole
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (oapi.UserRole, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) oapi.UserRole); ok {
		r0 = returnFunc(tokenString)
	} else {
		r0 = ret.Get(0).(oapi.UserRole)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTHelper_GetRoleClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoleClaim'
type MockJWTHelper_GetRoleClaim_Call struct {
	*mock.Call
}

// GetRoleClaim is a helper method to define mock.On call
//   - tokenString
func (_e *MockJWTHelper_Expecter) GetRoleClaim(tokenString interface{}) *MockJWTHelper_GetRoleClaim_Call {
	return &MockJWTHelper_GetRoleClaim_Call{Call: _e.mock.On("GetRoleClaim", tokenString)}
}

func (_c *MockJWTHelper_GetRoleClaim_Call) Run(run func(tokenString string)) *MockJWTHelper_GetRoleClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTHelper_GetRoleClaim_Call) Return(userRole oapi.UserRole, err error) *MockJWTHelper_GetRoleClaim_Call {
	_c.Call.Return(userRole, err)
	return _c
}

func (_c *MockJWTHelper_GetRoleClaim_Call) RunAndReturn(run func(tokenString string) (oapi.UserRole, error)) *MockJWTHelper_GetRoleClaim_Call {
	_c.Call.Return(run)
	return _c
}

// NewToken provides a mock function for the type MockJWTHelper
func (_mock *MockJWTHelper) NewToken(role oapi.UserRole) (string, error) {
	ret := _mock.Called(role)

	if len(ret) == 0 {
		panic("no return value specified for NewToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(oapi.UserRole) (string, error)); ok {
		return returnFunc(role)
	}
	if returnFunc, ok := ret.Get(0).(func(oapi.UserRole) string); ok {
		r0 = returnFunc(role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(oapi.UserRole) error); ok {
		r1 = returnFunc(role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTHelper_NewToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewToken'
type MockJWTHelper_NewToken_Call struct {
	*mock.Call
}

// NewToken is a helper method to define mock.On call
//   - role
func (_e *MockJWTHelper_Expecter) NewToken(role interface{}) *MockJWTHelper_NewToken_Call {
	return &MockJWTHelper_NewToken_Call{Call: _e.mock.On("NewToken", role)}
}

func (_c *MockJWTHelper_NewToken_Call) Run(run func(role oapi.UserRole)) *MockJWTHelper_NewToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(oapi.UserRole))
	})
	return _c
}

func (_c *MockJWTHelper_NewToken_Call) Return(s string, err error) *MockJWTHelper_NewToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJWTHelper_NewToken_Call) RunAndReturn(run func(role oapi.UserRole) (string, error)) *MockJWTHelper_NewToken_Call {
	_c.Call.Return(run)
	return _c
}
