// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oapi

import (
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerInterface creates a new instance of MockServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerInterface {
	mock := &MockServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerInterface is an autogenerated mock type for the ServerInterface type
type MockServerInterface struct {
	mock.Mock
}

type MockServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerInterface) EXPECT() *MockServerInterface_Expecter {
	return &MockServerInterface_Expecter{mock: &_m.Mock}
}

// GetPvz provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) GetPvz(c *gin.Context, params GetPvzParams) {
	_mock.Called(c, params)
	return
}

// MockServerInterface_GetPvz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPvz'
type MockServerInterface_GetPvz_Call struct {
	*mock.Call
}

// GetPvz is a helper method to define mock.On call
//   - c
//   - params
func (_e *MockServerInterface_Expecter) GetPvz(c interface{}, params interface{}) *MockServerInterface_GetPvz_Call {
	return &MockServerInterface_GetPvz_Call{Call: _e.mock.On("GetPvz", c, params)}
}

func (_c *MockServerInterface_GetPvz_Call) Run(run func(c *gin.Context, params GetPvzParams)) *MockServerInterface_GetPvz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(GetPvzParams))
	})
	return _c
}

func (_c *MockServerInterface_GetPvz_Call) Return() *MockServerInterface_GetPvz_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_GetPvz_Call) RunAndReturn(run func(c *gin.Context, params GetPvzParams)) *MockServerInterface_GetPvz_Call {
	_c.Run(run)
	return _c
}

// PostDummyLogin provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) PostDummyLogin(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockServerInterface_PostDummyLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostDummyLogin'
type MockServerInterface_PostDummyLogin_Call struct {
	*mock.Call
}

// PostDummyLogin is a helper method to define mock.On call
//   - c
func (_e *MockServerInterface_Expecter) PostDummyLogin(c interface{}) *MockServerInterface_PostDummyLogin_Call {
	return &MockServerInterface_PostDummyLogin_Call{Call: _e.mock.On("PostDummyLogin", c)}
}

func (_c *MockServerInterface_PostDummyLogin_Call) Run(run func(c *gin.Context)) *MockServerInterface_PostDummyLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockServerInterface_PostDummyLogin_Call) Return() *MockServerInterface_PostDummyLogin_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_PostDummyLogin_Call) RunAndReturn(run func(c *gin.Context)) *MockServerInterface_PostDummyLogin_Call {
	_c.Run(run)
	return _c
}

// PostLogin provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) PostLogin(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockServerInterface_PostLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostLogin'
type MockServerInterface_PostLogin_Call struct {
	*mock.Call
}

// PostLogin is a helper method to define mock.On call
//   - c
func (_e *MockServerInterface_Expecter) PostLogin(c interface{}) *MockServerInterface_PostLogin_Call {
	return &MockServerInterface_PostLogin_Call{Call: _e.mock.On("PostLogin", c)}
}

func (_c *MockServerInterface_PostLogin_Call) Run(run func(c *gin.Context)) *MockServerInterface_PostLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockServerInterface_PostLogin_Call) Return() *MockServerInterface_PostLogin_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_PostLogin_Call) RunAndReturn(run func(c *gin.Context)) *MockServerInterface_PostLogin_Call {
	_c.Run(run)
	return _c
}

// PostProducts provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) PostProducts(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockServerInterface_PostProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostProducts'
type MockServerInterface_PostProducts_Call struct {
	*mock.Call
}

// PostProducts is a helper method to define mock.On call
//   - c
func (_e *MockServerInterface_Expecter) PostProducts(c interface{}) *MockServerInterface_PostProducts_Call {
	return &MockServerInterface_PostProducts_Call{Call: _e.mock.On("PostProducts", c)}
}

func (_c *MockServerInterface_PostProducts_Call) Run(run func(c *gin.Context)) *MockServerInterface_PostProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockServerInterface_PostProducts_Call) Return() *MockServerInterface_PostProducts_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_PostProducts_Call) RunAndReturn(run func(c *gin.Context)) *MockServerInterface_PostProducts_Call {
	_c.Run(run)
	return _c
}

// PostPvz provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) PostPvz(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockServerInterface_PostPvz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostPvz'
type MockServerInterface_PostPvz_Call struct {
	*mock.Call
}

// PostPvz is a helper method to define mock.On call
//   - c
func (_e *MockServerInterface_Expecter) PostPvz(c interface{}) *MockServerInterface_PostPvz_Call {
	return &MockServerInterface_PostPvz_Call{Call: _e.mock.On("PostPvz", c)}
}

func (_c *MockServerInterface_PostPvz_Call) Run(run func(c *gin.Context)) *MockServerInterface_PostPvz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockServerInterface_PostPvz_Call) Return() *MockServerInterface_PostPvz_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_PostPvz_Call) RunAndReturn(run func(c *gin.Context)) *MockServerInterface_PostPvz_Call {
	_c.Run(run)
	return _c
}

// PostPvzPvzIdCloseLastReception provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) PostPvzPvzIdCloseLastReception(c *gin.Context, pvzId types.UUID) {
	_mock.Called(c, pvzId)
	return
}

// MockServerInterface_PostPvzPvzIdCloseLastReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostPvzPvzIdCloseLastReception'
type MockServerInterface_PostPvzPvzIdCloseLastReception_Call struct {
	*mock.Call
}

// PostPvzPvzIdCloseLastReception is a helper method to define mock.On call
//   - c
//   - pvzId
func (_e *MockServerInterface_Expecter) PostPvzPvzIdCloseLastReception(c interface{}, pvzId interface{}) *MockServerInterface_PostPvzPvzIdCloseLastReception_Call {
	return &MockServerInterface_PostPvzPvzIdCloseLastReception_Call{Call: _e.mock.On("PostPvzPvzIdCloseLastReception", c, pvzId)}
}

func (_c *MockServerInterface_PostPvzPvzIdCloseLastReception_Call) Run(run func(c *gin.Context, pvzId types.UUID)) *MockServerInterface_PostPvzPvzIdCloseLastReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(types.UUID))
	})
	return _c
}

func (_c *MockServerInterface_PostPvzPvzIdCloseLastReception_Call) Return() *MockServerInterface_PostPvzPvzIdCloseLastReception_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_PostPvzPvzIdCloseLastReception_Call) RunAndReturn(run func(c *gin.Context, pvzId types.UUID)) *MockServerInterface_PostPvzPvzIdCloseLastReception_Call {
	_c.Run(run)
	return _c
}

// PostPvzPvzIdDeleteLastProduct provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) PostPvzPvzIdDeleteLastProduct(c *gin.Context, pvzId types.UUID) {
	_mock.Called(c, pvzId)
	return
}

// MockServerInterface_PostPvzPvzIdDeleteLastProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostPvzPvzIdDeleteLastProduct'
type MockServerInterface_PostPvzPvzIdDeleteLastProduct_Call struct {
	*mock.Call
}

// PostPvzPvzIdDeleteLastProduct is a helper method to define mock.On call
//   - c
//   - pvzId
func (_e *MockServerInterface_Expecter) PostPvzPvzIdDeleteLastProduct(c interface{}, pvzId interface{}) *MockServerInterface_PostPvzPvzIdDeleteLastProduct_Call {
	return &MockServerInterface_PostPvzPvzIdDeleteLastProduct_Call{Call: _e.mock.On("PostPvzPvzIdDeleteLastProduct", c, pvzId)}
}

func (_c *MockServerInterface_PostPvzPvzIdDeleteLastProduct_Call) Run(run func(c *gin.Context, pvzId types.UUID)) *MockServerInterface_PostPvzPvzIdDeleteLastProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(types.UUID))
	})
	return _c
}

func (_c *MockServerInterface_PostPvzPvzIdDeleteLastProduct_Call) Return() *MockServerInterface_PostPvzPvzIdDeleteLastProduct_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_PostPvzPvzIdDeleteLastProduct_Call) RunAndReturn(run func(c *gin.Context, pvzId types.UUID)) *MockServerInterface_PostPvzPvzIdDeleteLastProduct_Call {
	_c.Run(run)
	return _c
}

// PostReceptions provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) PostReceptions(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockServerInterface_PostReceptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostReceptions'
type MockServerInterface_PostReceptions_Call struct {
	*mock.Call
}

// PostReceptions is a helper method to define mock.On call
//   - c
func (_e *MockServerInterface_Expecter) PostReceptions(c interface{}) *MockServerInterface_PostReceptions_Call {
	return &MockServerInterface_PostReceptions_Call{Call: _e.mock.On("PostReceptions", c)}
}

func (_c *MockServerInterface_PostReceptions_Call) Run(run func(c *gin.Context)) *MockServerInterface_PostReceptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockServerInterface_PostReceptions_Call) Return() *MockServerInterface_PostReceptions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_PostReceptions_Call) RunAndReturn(run func(c *gin.Context)) *MockServerInterface_PostReceptions_Call {
	_c.Run(run)
	return _c
}

// PostRegister provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) PostRegister(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockServerInterface_PostRegister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostRegister'
type MockServerInterface_PostRegister_Call struct {
	*mock.Call
}

// PostRegister is a helper method to define mock.On call
//   - c
func (_e *MockServerInterface_Expecter) PostRegister(c interface{}) *MockServerInterface_PostRegister_Call {
	return &MockServerInterface_PostRegister_Call{Call: _e.mock.On("PostRegister", c)}
}

func (_c *MockServerInterface_PostRegister_Call) Run(run func(c *gin.Context)) *MockServerInterface_PostRegister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockServerInterface_PostRegister_Call) Return() *MockServerInterface_PostRegister_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_PostRegister_Call) RunAndReturn(run func(c *gin.Context)) *MockServerInterface_PostRegister_Call {
	_c.Run(run)
	return _c
}
