// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pwz_service

import (
	"avito/internal/oapi"
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddProduct provides a mock function for the type MockRepository
func (_mock *MockRepository) AddProduct(ctx context.Context, pvdID uuid.UUID, productType oapi.ProductType) (oapi.Product, error) {
	ret := _mock.Called(ctx, pvdID, productType)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 oapi.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, oapi.ProductType) (oapi.Product, error)); ok {
		return returnFunc(ctx, pvdID, productType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, oapi.ProductType) oapi.Product); ok {
		r0 = returnFunc(ctx, pvdID, productType)
	} else {
		r0 = ret.Get(0).(oapi.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, oapi.ProductType) error); ok {
		r1 = returnFunc(ctx, pvdID, productType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AddProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduct'
type MockRepository_AddProduct_Call struct {
	*mock.Call
}

// AddProduct is a helper method to define mock.On call
//   - ctx
//   - pvdID
//   - productType
func (_e *MockRepository_Expecter) AddProduct(ctx interface{}, pvdID interface{}, productType interface{}) *MockRepository_AddProduct_Call {
	return &MockRepository_AddProduct_Call{Call: _e.mock.On("AddProduct", ctx, pvdID, productType)}
}

func (_c *MockRepository_AddProduct_Call) Run(run func(ctx context.Context, pvdID uuid.UUID, productType oapi.ProductType)) *MockRepository_AddProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(oapi.ProductType))
	})
	return _c
}

func (_c *MockRepository_AddProduct_Call) Return(product oapi.Product, err error) *MockRepository_AddProduct_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockRepository_AddProduct_Call) RunAndReturn(run func(ctx context.Context, pvdID uuid.UUID, productType oapi.ProductType) (oapi.Product, error)) *MockRepository_AddProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CheckPVZ provides a mock function for the type MockRepository
func (_mock *MockRepository) CheckPVZ(ctx context.Context, pvzID uuid.UUID) error {
	ret := _mock.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for CheckPVZ")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, pvzID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CheckPVZ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPVZ'
type MockRepository_CheckPVZ_Call struct {
	*mock.Call
}

// CheckPVZ is a helper method to define mock.On call
//   - ctx
//   - pvzID
func (_e *MockRepository_Expecter) CheckPVZ(ctx interface{}, pvzID interface{}) *MockRepository_CheckPVZ_Call {
	return &MockRepository_CheckPVZ_Call{Call: _e.mock.On("CheckPVZ", ctx, pvzID)}
}

func (_c *MockRepository_CheckPVZ_Call) Run(run func(ctx context.Context, pvzID uuid.UUID)) *MockRepository_CheckPVZ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_CheckPVZ_Call) Return(err error) *MockRepository_CheckPVZ_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CheckPVZ_Call) RunAndReturn(run func(ctx context.Context, pvzID uuid.UUID) error) *MockRepository_CheckPVZ_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePVZ provides a mock function for the type MockRepository
func (_mock *MockRepository) CreatePVZ(ctx context.Context, city oapi.PVZCity) (oapi.PVZ, error) {
	ret := _mock.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for CreatePVZ")
	}

	var r0 oapi.PVZ
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.PVZCity) (oapi.PVZ, error)); ok {
		return returnFunc(ctx, city)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, oapi.PVZCity) oapi.PVZ); ok {
		r0 = returnFunc(ctx, city)
	} else {
		r0 = ret.Get(0).(oapi.PVZ)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, oapi.PVZCity) error); ok {
		r1 = returnFunc(ctx, city)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreatePVZ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePVZ'
type MockRepository_CreatePVZ_Call struct {
	*mock.Call
}

// CreatePVZ is a helper method to define mock.On call
//   - ctx
//   - city
func (_e *MockRepository_Expecter) CreatePVZ(ctx interface{}, city interface{}) *MockRepository_CreatePVZ_Call {
	return &MockRepository_CreatePVZ_Call{Call: _e.mock.On("CreatePVZ", ctx, city)}
}

func (_c *MockRepository_CreatePVZ_Call) Run(run func(ctx context.Context, city oapi.PVZCity)) *MockRepository_CreatePVZ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(oapi.PVZCity))
	})
	return _c
}

func (_c *MockRepository_CreatePVZ_Call) Return(pVZ oapi.PVZ, err error) *MockRepository_CreatePVZ_Call {
	_c.Call.Return(pVZ, err)
	return _c
}

func (_c *MockRepository_CreatePVZ_Call) RunAndReturn(run func(ctx context.Context, city oapi.PVZCity) (oapi.PVZ, error)) *MockRepository_CreatePVZ_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLastProduct provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteLastProduct(ctx context.Context, pvzID uuid.UUID) error {
	ret := _mock.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLastProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, pvzID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteLastProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLastProduct'
type MockRepository_DeleteLastProduct_Call struct {
	*mock.Call
}

// DeleteLastProduct is a helper method to define mock.On call
//   - ctx
//   - pvzID
func (_e *MockRepository_Expecter) DeleteLastProduct(ctx interface{}, pvzID interface{}) *MockRepository_DeleteLastProduct_Call {
	return &MockRepository_DeleteLastProduct_Call{Call: _e.mock.On("DeleteLastProduct", ctx, pvzID)}
}

func (_c *MockRepository_DeleteLastProduct_Call) Run(run func(ctx context.Context, pvzID uuid.UUID)) *MockRepository_DeleteLastProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_DeleteLastProduct_Call) Return(err error) *MockRepository_DeleteLastProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteLastProduct_Call) RunAndReturn(run func(ctx context.Context, pvzID uuid.UUID) error) *MockRepository_DeleteLastProduct_Call {
	_c.Call.Return(run)
	return _c
}

// FinishReception provides a mock function for the type MockRepository
func (_mock *MockRepository) FinishReception(ctx context.Context, pvzID uuid.UUID) (oapi.Reception, error) {
	ret := _mock.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for FinishReception")
	}

	var r0 oapi.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (oapi.Reception, error)); ok {
		return returnFunc(ctx, pvzID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) oapi.Reception); ok {
		r0 = returnFunc(ctx, pvzID)
	} else {
		r0 = ret.Get(0).(oapi.Reception)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FinishReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishReception'
type MockRepository_FinishReception_Call struct {
	*mock.Call
}

// FinishReception is a helper method to define mock.On call
//   - ctx
//   - pvzID
func (_e *MockRepository_Expecter) FinishReception(ctx interface{}, pvzID interface{}) *MockRepository_FinishReception_Call {
	return &MockRepository_FinishReception_Call{Call: _e.mock.On("FinishReception", ctx, pvzID)}
}

func (_c *MockRepository_FinishReception_Call) Run(run func(ctx context.Context, pvzID uuid.UUID)) *MockRepository_FinishReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_FinishReception_Call) Return(reception oapi.Reception, err error) *MockRepository_FinishReception_Call {
	_c.Call.Return(reception, err)
	return _c
}

func (_c *MockRepository_FinishReception_Call) RunAndReturn(run func(ctx context.Context, pvzID uuid.UUID) (oapi.Reception, error)) *MockRepository_FinishReception_Call {
	_c.Call.Return(run)
	return _c
}

// ListPVZInfo provides a mock function for the type MockRepository
func (_mock *MockRepository) ListPVZInfo(ctx context.Context, startDate time.Time, endDate time.Time, limit int, page int) ([]oapi.GetPvzResponseItem, error) {
	ret := _mock.Called(ctx, startDate, endDate, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for ListPVZInfo")
	}

	var r0 []oapi.GetPvzResponseItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) ([]oapi.GetPvzResponseItem, error)); ok {
		return returnFunc(ctx, startDate, endDate, limit, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, int, int) []oapi.GetPvzResponseItem); ok {
		r0 = returnFunc(ctx, startDate, endDate, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]oapi.GetPvzResponseItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, int, int) error); ok {
		r1 = returnFunc(ctx, startDate, endDate, limit, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListPVZInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPVZInfo'
type MockRepository_ListPVZInfo_Call struct {
	*mock.Call
}

// ListPVZInfo is a helper method to define mock.On call
//   - ctx
//   - startDate
//   - endDate
//   - limit
//   - page
func (_e *MockRepository_Expecter) ListPVZInfo(ctx interface{}, startDate interface{}, endDate interface{}, limit interface{}, page interface{}) *MockRepository_ListPVZInfo_Call {
	return &MockRepository_ListPVZInfo_Call{Call: _e.mock.On("ListPVZInfo", ctx, startDate, endDate, limit, page)}
}

func (_c *MockRepository_ListPVZInfo_Call) Run(run func(ctx context.Context, startDate time.Time, endDate time.Time, limit int, page int)) *MockRepository_ListPVZInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockRepository_ListPVZInfo_Call) Return(getPvzResponseItems []oapi.GetPvzResponseItem, err error) *MockRepository_ListPVZInfo_Call {
	_c.Call.Return(getPvzResponseItems, err)
	return _c
}

func (_c *MockRepository_ListPVZInfo_Call) RunAndReturn(run func(ctx context.Context, startDate time.Time, endDate time.Time, limit int, page int) ([]oapi.GetPvzResponseItem, error)) *MockRepository_ListPVZInfo_Call {
	_c.Call.Return(run)
	return _c
}

// StartReception provides a mock function for the type MockRepository
func (_mock *MockRepository) StartReception(ctx context.Context, pvzID uuid.UUID) (oapi.Reception, error) {
	ret := _mock.Called(ctx, pvzID)

	if len(ret) == 0 {
		panic("no return value specified for StartReception")
	}

	var r0 oapi.Reception
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (oapi.Reception, error)); ok {
		return returnFunc(ctx, pvzID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) oapi.Reception); ok {
		r0 = returnFunc(ctx, pvzID)
	} else {
		r0 = ret.Get(0).(oapi.Reception)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, pvzID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_StartReception_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartReception'
type MockRepository_StartReception_Call struct {
	*mock.Call
}

// StartReception is a helper method to define mock.On call
//   - ctx
//   - pvzID
func (_e *MockRepository_Expecter) StartReception(ctx interface{}, pvzID interface{}) *MockRepository_StartReception_Call {
	return &MockRepository_StartReception_Call{Call: _e.mock.On("StartReception", ctx, pvzID)}
}

func (_c *MockRepository_StartReception_Call) Run(run func(ctx context.Context, pvzID uuid.UUID)) *MockRepository_StartReception_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_StartReception_Call) Return(reception oapi.Reception, err error) *MockRepository_StartReception_Call {
	_c.Call.Return(reception, err)
	return _c
}

func (_c *MockRepository_StartReception_Call) RunAndReturn(run func(ctx context.Context, pvzID uuid.UUID) (oapi.Reception, error)) *MockRepository_StartReception_Call {
	_c.Call.Return(run)
	return _c
}
